### ISSUE TITLE
filterCache[layerId] is not a function in 6.1.0

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/ol-mapbox-style#261]
Example with 6.1.0
https://codesandbox.io/s/cluster-6ie41
There is an error "filterCache[layerId] is not a function".

It works with 6.0.1
https://codesandbox.io/s/cluster-wqgdq

**Comment by MichalK6677** [comment]
It seems it's because "@mapbox/mapbox-gl-style-spec": "^13.11.0". It installs 13.13.0 and there is a breaking change in:
https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/feature_filter/index.js

And create filter return value is changed:
![image](https://user-images.githubusercontent.com/3100059/77458215-20f0e380-6dfe-11ea-879a-b3e35adaf15a.png)

**Comment by PacoDu** [comment]
I'm facing the same error, thanks for the workaround !

**Comment by ahocevar** [comment]
Thanks for your research @MichalK6677, with this information it was easy to fix the issue. See #262.

**Comment by ZakarFin** [comment]
Just for someone googling we hit this with 5.0.2 as well.
